### ISSUE TITLE
Bug: MoviePosterImage frame is affected by animation

### ISSUE THREAD

**Issue by SuperWomble** [Dimillian/MovieSwiftUI#10]
Using Simulator on 10.14.5, Xcode beta2

**Problem**

`MoviePosterImage` locations are being affected by the (opacity) animation being applied to them. 

As each movie poster image is populated (via the ImageService callback), the view will unfade, but will also move, with a jarring effect.

To see this most clearly, launch in the Simulator with `SlowAnimations` enabled. Then alternate between the "Popular" and "Top Rated" tabs quickly.

**Problem Area**

`MoviePosterImage.swift`

```
struct PosterStyle: ViewModifier {
    let loaded: Bool
    func body(content: Content) -> some View {
        return content
			.frame(width: 100, height: 150)
            .cornerRadius(5)
        	.opacity(loaded ? 1 : 0.1)
            .shadow(radius: 8)
    }
}
```
It would appear that applying `.animation(.basic())` in `MoviePosterImage` is actually applying the animation to all properties, `frame` included.

I have attempted to work around this, but have not yet succeeded.

**Comment by debizworld** [comment]
Thank You
