### ISSUE TITLE
Building a Mac with xcode Version 11.0 beta 3 (11M362v) failed

### ISSUE THREAD

**Issue by AnneBlair** [Dimillian/MovieSwiftUI#16]
![WX20190705-174152](https://user-images.githubusercontent.com/17793074/60713837-5726c400-9f4c-11e9-8dd5-56f42e21a997.png)

**Comment by Dimillian** [comment]
Yeah, for some reason my Swift Package doesn't compile for UIKitForMac anymore. I guess it's an Xcode bug, will see if I can find a workaround until next beta.

**Comment by AnneBlair** [comment]
Thank you, it seems that I am not alone in this situation.

**Comment by liemvo** [comment]
@AnneBlair It builds success with me with the same XCode version.

**Comment by Dimillian** [comment]
@liemvo Really? You can run the app on your macOS with Xcode beta 3?

**Comment by liemvo** [comment]
Sure!

**Comment by Dimillian** [comment]
It now works with beta 4 :)
