### ISSUE TITLE
Images section - MovieBackdropImage fails to render

### ISSUE THREAD

**Issue by krasi-pl** [Dimillian/MovieSwiftUI#18]
I have noticed that Images section fails to update with proper images. Did some investigation and it seems that i.e wrapping placeholder like that:
  ```
              ZStack {
                Text ("BUG?")
                Rectangle()
                    .frame(maxHeight: fill ? 50 : 300)
                    .aspectRatio(500/300, contentMode: fill || !isExpanded ? .fill : .fit)
                    .foregroundColor(.gray)
                    .opacity(0.1)
              }
```
Solves the issue, yet it's supper hacky and I have no clue, why it fails to render in first place. Any ideas?

**Comment by Dimillian** [comment]
Thanks for reminding me about it. Nah it's because I'm still using a view wrapped in Geometry reader (the one used at top of the MovieDetail view). And for the row it needs to be a simpler one, will fix very soon :)

**Comment by Dimillian** [comment]
It's fixed on latest commit :)
