### ISSUE TITLE
TabbedView forgets state

### ISSUE THREAD

**Issue by hactar** [Dimillian/MovieSwiftUI#23]
If you tap a movie in the movies tab, then tap the "My Lists" tab, then switch back to the movies tab, the app forgets that you tapped a movie and resets to the standard view.

I'm currently playing around with TabbedView in a different project and would be interested on how you would solve this. As far as I understand views are supposed to be "disposable", but storing the state of the subviews in the TabbedView itself feels wrong too...

**Comment by Dimillian** [comment]
Yup, IMO if this not handled from Apple it’ll feel weird, I don’t want to deal with restoring a whole NavigationView state for example. So I’ll really hope Apple will implement it within SwiftUI.

**Comment by lightandshadow68** [comment]
Some kind of routing mechanism might be an appropriate solution. This was very difficult to implement in UIKit but the more declarative approach of SwiftUI should improve things greatly.

**Comment by lightandshadow68** [comment]
The ability to go directly to a movie in the Movies tab via notification (such as, when it is released) would be another use case for routing.

**Comment by Dimillian** [comment]
Yeah, a router sound very very easy.
You just do a case stringPath: return MovieDetailView(movieId) and done. 
Don't know if I'll support notifications yet, but I might do a today widget, so it would be a good occasion to do it.

**Comment by adesugbaa** [comment]
Great job.

Any update or workaround on this? I have been holding out on SwiftUI because of this issue. It is very un-iOS, losing state when tabview is switched.

**Comment by JS1010111** [comment]
I did not tried the following, but it seems the way to go until Apple fixes this.

Workaround: https://gist.github.com/Amzd/2eb5b941865e8c5cccf149e6e07c8810
From: https://github.com/ryangittings/swiftui-bugs
