### ISSUE TITLE
Click itemView in ScrollView , the app got a  crash

### ISSUE THREAD

**Issue by WhityLL** [Dimillian/MovieSwiftUI#31]
Click itemView in ScrollView , the app got a  crash.
in  MoviesHomePage grid style , click see all
in MovieDetail  keywords cell , click title area got a  recyle push/pop  then  crash

is it the iOS13's bug ?

**Comment by WhityLL** [comment]
when Scrollview contains navigationlink, navigationlink will not navigate successfully??

**Comment by wazowski78** [comment]
It seems there are some lacks in UIKit and SwiftUI, navigation between views is not as expected to be. 

I have manage to go forward and back adding a intermediate view in .onload function of the MovieDetail view body.

I use a dispatch async to load an empty .actionsheet shown a message like: "Loading information..." and adding another dispatch async after 0.5 seconds, what makes a loading view appear and disappear. 

I have notice, that loading a intermediate view, helps the controller to take the whole control of the navigation process. I know, it sounds weird, but it is not crashing anymore. I am sure there are other solutions, but this one worked for me.
