### ISSUE TITLE
Trailer implementation

### ISSUE THREAD

**Issue by wazowski78** [Dimillian/MovieSwiftUI#32]
Hi, first I have to say it is a nice job. Great SwiftUI example! 

One question, are you going to implement the trailer option of the film?

Thank you!

**Comment by wazowski78** [comment]
Thank you! I have managed to implement them myself.

**Comment by Dimillian** [comment]
Maybe you can open a PR so we can all have it ? :)

**Comment by wazowski78** [comment]
Well, I am facing more problems than the trailer implementation. For example, when navigating through views. These are the problems I am facing at this moment:

· When you tap on back buttons, the app crashes. I have read about it, and it seems to be a problem with the UIKit and SwiftUI, I have managed to stop this behavior using a action sheet as a loader view. It is very nasty but it works. Now it is not crashing every time I tap back buttons. 

· The grid view in home view makes the app crash too. If I reduce the number of films to load on each scrollview, the app crashes less, but sometimes still crashing.

· Region picker is not working properly, or it does not work as I suppose it to work. I can not change the region selected with the picker, so I have to change the picker to a list or other controller.

· Added trailers to Movie model. Just added the Youtube video id, and make the url request to a new view.

I will try to make it clear, but I am not using the whole app, just parts of it. Once organized, I should make a PR.

**Comment by wazowski78** [comment]
I have implemented trailers like this:
![IMG_2511](https://user-images.githubusercontent.com/5912641/69878300-d682ae80-12c4-11ea-9c2b-ad765dca6e0c.PNG)

**Comment by Dimillian** [comment]
That's quite nice already :)

Yeah, there is a lot of crashes within SwiftUI TabbedView and NavigationView and until apple fixes them, nothing much I can do unfortunately :/

**Comment by bark1n9** [comment]
> Well, I am facing more problems than the trailer implementation. For example, when navigating through views. These are the problems I am facing at this moment:
> 
> · When you tap on back buttons, the app crashes. I have read about it, and it seems to be a problem with the UIKit and SwiftUI, I have managed to stop this behavior using a action sheet as a loader view. It is very nasty but it works. Now it is not crashing every time I tap back buttons.
> 
> · The grid view in home view makes the app crash too. If I reduce the number of films to load on each scrollview, the app crashes less, but sometimes still crashing.
> 
> · Region picker is not working properly, or it does not work as I suppose it to work. I can not change the region selected with the picker, so I have to change the picker to a list or other controller.
> 
> · Added trailers to Movie model. Just added the Youtube video id, and make the url request to a new view.
> 
> I will try to make it clear, but I am not using the whole app, just parts of it. Once organized, I should make a PR.

Have you made a PR? I’m currently trying to deal with the “back” issue, but no luck.

Would love to see how you dealt with it...

**Comment by Dimillian** [comment]
I'm currently working on trailer as next feature. So if you want to make it yourself as a PR, now it's the time :p
