### ISSUE TITLE
error when building

### ISSUE THREAD

**Issue by lexuanquynh** [Dimillian/MovieSwiftUI#39]
![1](https://user-images.githubusercontent.com/17588791/74129502-13ebac80-4c23-11ea-9365-f5de5f5f3004.png)

**Comment by lexuanquynh** [comment]
package 'UI' requires minimum Swift language version 5.2 which is not supported by the current tools version (5.1.0)
how to update?

**Comment by lexuanquynh** [comment]
have you used Xcode 11.4 Beta?

**Comment by Dimillian** [comment]
I'm using the new Xcode 11.4 beta 1, so I've updated the Swift version to 5.2. You can download it from Apple dev center and then you'll be able compile the app

**Comment by lexuanquynh** [comment]
I change  swiftLanguageVersions: [
        .version("5.1.0")
    ] 
and resolved my problems.
