### ISSUE TITLE
Project Compile Failed

### ISSUE THREAD

**Issue by sandeepsuthar** [Dimillian/MovieSwiftUI#4]
I downloaded project and when start compile then it failed.
Please suggest me to work properly.
![Screenshot 2019-06-23 at 11 55 11 am](https://user-images.githubusercontent.com/9675872/59972517-335b9980-95ae-11e9-8218-6019e8c6eee8.png)
![Screenshot 2019-06-23 at 11 55 22 am](https://user-images.githubusercontent.com/9675872/59972519-3e162e80-95ae-11e9-80c2-ce65e51ff628.png)
![Screenshot 2019-06-23 at 11 55 31 am](https://user-images.githubusercontent.com/9675872/59972523-466e6980-95ae-11e9-8ab9-d274d85efe23.png)
![Screenshot 2019-06-23 at 11 55 38 am](https://user-images.githubusercontent.com/9675872/59972525-4ec6a480-95ae-11e9-8650-f4ac571ac273.png)

**Comment by svaz** [comment]
Yup +1 for the above !!!

**Comment by Dimillian** [comment]
You need to update to Xcode beta 2.

**Comment by rugmangathan** [comment]
@Dimillian I'm on Xcode beta 2. I'm facing below issue in console while running app in Simulator.

[general] CFLocaleCopyCurrent() failed to look up current locale via 'AppleLocale' and 'AppleLanguages' in user preferences; falling back to locale identifier 'en_US' as the default. Consider checking Console for sandbox violations from this process for reading from preferences, or enabling CoreFoundation debug logging for more information. This will only be logged once.

**Comment by Dimillian** [comment]
There is ton on output in console because it’s a beta built. But if the app load and you can see stuff on screen it should all be good :)

**Comment by Dimillian** [comment]
I guess you should delete and recreate the simulator maybe too, it should help.

**Comment by svaz** [comment]
Update to Xcode beta2 and now it all works. Thanks

**Comment by anm8tr** [comment]
I just downloaded and ran in Xcode Beta 2, works perfect!

**Comment by rugmangathan** [comment]
> There is ton on output in console because it’s a beta build. But if the app load and you can see stuff on screen it should all be good :)

Thanks for the info. Seems like [https://www.themoviedb.org/](url) is not accessible from my end. May be blocked by ISP.

**Comment by sandeepsuthar** [comment]
@Dimillian Thank you for quick response.
Really appreciated!!!!

**Comment by Dimillian** [comment]
I'll close this one, don't hesitate to open a new one if any problem occur.
