### ISSUE TITLE
View Preview - UI Package

### ISSUE THREAD

**Issue by mkkroliks** [Dimillian/MovieSwiftUI#40]
Is there any way to preview a views in the UI package? For example PopularityBadge.swift? I'm getting such an error.

![image](https://user-images.githubusercontent.com/2151961/75976241-55960d00-5eda-11ea-9569-892a142dcb53.png)

**Comment by Dimillian** [comment]
Yep. It's bugging me too and I have no idea how to resolve this one.

**Comment by mkkroliks** [comment]
@Dimillian Did it work with previous versions of Xcode? I'm trying to find some workaround.

**Comment by Dimillian** [comment]
Not that I recall. And it's still not working on the latest beta.
