### ISSUE TITLE
Segmented state not shown

### ISSUE THREAD

**Issue by ristkof** [Dimillian/MovieSwiftUI#45]
Not sure if somebody noticed this already? I tried this in the simulator (iPhone 11 Pro Max 13.4)

![Screen Recording 2020-03-27 at 16 29 24](https://user-images.githubusercontent.com/211518/77773004-4aea1600-7049-11ea-9b62-1176446bb1d8.gif)

**Comment by Dimillian** [comment]
You’re talking about the animation?

**Comment by ristkof** [comment]
No about the segmented state control (now playing / upcoming / trending) under the search bar. The title and the content changes correctly but the segmented state control doesn't. Specifically the segmented state control updates correctly for a while and then it seems stuck on "trending" after that.

I should recheck in simulator and on device, etc... so if you can't reproduce the same behavior immediately, maybe it was just a temporary issue, and ignore.

**Comment by Dimillian** [comment]
You’re write I can reproduce it. I’ll refactor the whole component anyway it’s just not working correctly.

**Comment by bark1n9** [comment]
@Dimillian were you able to fix this?

**Comment by Dimillian** [comment]
Didn’t looked at it yet. PR welcome :)

**Comment by bark1n9** [comment]
@Dimillian haha fair enough :) I tried to fix it, but can't seem to figure out what's wrong. It actually looks like an issue with SwiftUI because it work fine on iOS 13.3 but not on 13.4

**Comment by Dimillian** [comment]
It’s because this view is part of the header of the List, and as you change tab the list reload itself and the segmented custom view is reset. Somehow it should be outside of the List, but I don’t see how it would scroll with content then :/

**Comment by bark1n9** [comment]
@Dimillian makes sense, will look into it. Can't make any promises tho :)

**Comment by Dimillian** [comment]
It was months ago last time I’ve tried to solve it. Maybe a new approach would be good :)

**Comment by bark1n9** [comment]
I know this is not the ideal solution but in the meantime simply adding id: \.self in the ScrollableSelector ForEach part fixes this issue. Like so: 

 var body: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(alignment: .center, spacing: 12) {
                ForEach(0 ..< items.count, id: \.self) {
                    self.text(for: $0)
                }
            }
            .padding([.leading, .trailing], 4)
        }
        .frame(height: 36)
        .background(Color.steam_background)
        .cornerRadius(8)
    }

**Comment by Dimillian** [comment]
Tried change nothing

```
  ScrollView(.horizontal, showsIndicators: false) {
            HStack(alignment: .center, spacing: 12) {
                ForEach(0 ..< items.count, id: \.self) {
                    self.text(for: $0).id($0)
                }
            }
            .padding([.leading, .trailing], 4)
        }
        .frame(height: 36)
        .background(Color.steam_background)
        .cornerRadius(8)
```

**Comment by bark1n9** [comment]
Interesting, works fine for me (at least on Simulator)
