### ISSUE TITLE
App not usable in Xcode 11 Beta2 simulator

### ISSUE THREAD

**Issue by cioraneanu** [Dimillian/MovieSwiftUI#5]
Wanted to check if there is an issue on my end or if this is happening for everyone. 
Running the app on the emulator is painfully slow. Every touch requires 10-15 secs to be performed. I don't have a real device with iOS 13 to test it, but wanted to know if it's an app optimization issue or beta simulator issue.

**Comment by anm8tr** [comment]
It's your system! I just downloaded and ran an iPhone Xr sim, works perfectly!  But I have SSD's and tons of ram on my iMAc.

**Comment by cioraneanu** [comment]
You're right. Apparently I just needed give the Mac a good old restart. Everything work great now.

**Comment by SuperWomble** [comment]
It's not just his system... it's beta2 going nuts when using previews or the Simulator.
Keep Activity Monitor handy. Look for SimRenderServer going rampant, gobbling up CPU cycles and a lot of RAM. If you're running the Simulator, you'll have to quit it, restart it.

**Comment by anm8tr** [comment]
Mine works fine, so what do you call that? Lol
