### ISSUE TITLE
iOS 14 Beta 4 & 5 crash

### ISSUE THREAD

**Issue by bark1n9** [Dimillian/MovieSwiftUI#51]
When scrolling through MoviesList or MovieDetail, the app crashes: Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [inf nan]

**Comment by bark1n9** [comment]
This seems like a bug with SwiftUI, can anyone else confirm?

**Comment by bark1n9** [comment]
@Dimillian This crash still exists on iOS 14 Beta 5. Do you know if this is a SwiftUI issue or issue with the app itself?

**Comment by bark1n9** [comment]
@Dimillian Any idea on why this might be happening?

**Comment by bark1n9** [comment]
@Dimillian Any idea on a fix? I'm trying to build a similar app to learn SwiftUI and my app is also crashing because of this.

**Comment by Dimillian** [comment]
I don't have any idea for now, I guess store update across the app don't play nice anymore :/ I'll try to take time to dig into it later on.

**Comment by bark1n9** [comment]
@Dimillian Ok thank you. Could this be a SwiftUI issue, should I spend some time trying to fix it or could it be fixed on a future Beta?

**Comment by bark1n9** [comment]
Fixed in Beta 6.
