### ISSUE TITLE
Confused about OffsetTopPreferenceKey

### ISSUE THREAD

**Issue by rubybrowncoat** [Dimillian/MovieSwiftUI#53]
I know that this may not be the appropriate place to ask for this, so I apologise in advance if that's the case.

Could you explain the purpose of these lines (and of the `OffsetTopPreferenceKey`)?

https://github.com/Dimillian/MovieSwiftUI/blob/2897f8dfd3ea8370fbecacf56a8516f25d71efe8/MovieSwift/Packages/UI/Sources/UI/fields/SearchField.swift#L60-L61

I see you are listening for `onPreferenceChange` on the SearchFields but the expected end result escapes me. I tried removing the two lines but I haven't spotted any difference, at least not on the iOS Simulator.

**Comment by Dimillian** [comment]
If I remember correctly it's to dismiss the keyboard on scroll.
